substitutions:
  name: "salt-sentry"

esphome:
  name: "${name}"
  project:
    name: lemcke-solutions.salt-sentry
    version: "v2.1"

esp8266:
  board: esp_wroom_02

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "1285242ebef1545569b423bdccb15bcf"

dashboard_import:
  package_import_url: github://Lemcke-solutions/SaltSentryManuals/blob/main/ESPHome.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Salt-Sentry Fallback Hotspot"
    password: "i6DInw0TyVYt"

captive_portal:
    
i2c:
  sda: 2
  scl: 14
  scan: true

globals:
   - id: full_cm
     type: float
     initial_value: '5'
   - id: empty_cm
     type: float
     initial_value: '35'

sensor:
  - platform: vl53l0x
    id: distance_m
    address: 0x29
    update_interval: 60s
    long_range: false
    internal: true
  - platform: template
    unit_of_measurement: cm
    icon: mdi:arrow-expand-down
    name: distance
    id: distance
    lambda: |- 
      return id(distance_m).state * 100;
  - platform: template
    name: "percentage"
    unit_of_measurement: '%'
    icon: mdi:percent
    lambda: |-
      if (id(distance).state < id(full_cm)) {
        return 100;
      }
      
      if (id(distance).state > id(empty_cm)) {
        return 0;
      }
      
      return 100 - (id(distance).state - id(full_cm))  / ((id(empty_cm) - id(full_cm)) / 100);
    update_interval: 60s
